name: NodeJS with Webpack

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  build:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

  build-and-upload:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
        mkdir -p artifacts
        cp -r out artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: output_artifact
        path: artifacts

  publish:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: output_artifact
        path: artifacts

    - name: Status Check
      run: |
        echo "ls ==================="
        ls -la
        echo "==================="
        echo "pwd ==================="
        pwd
        echo "==================="

        echo "tree ==================="
        tree
        echo "==================="

    - name: Create index_copy.html
      run: |
        cp ./artifacts/out/index.html ./artifacts/out/index_copy.html

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ftpupload.net
        username: b22_40632936
        password: ${{ secrets.ftp_password }}
        local-dir: ./artifacts/out/
        server-dir: ./htdocs/github_test/
